package tablifi.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import tablifi.ExtractAnnotationsHelper;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.Locale;

public class TablifiForm {
    public static void main(String[] args) {
        JFrame frame = new JFrame("Tablifi");
        frame.setContentPane(new TablifiForm().mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        }

        JButton selectFolderButton;
private JPanel mainPanel;
private JTextField folderPathField;
        JButton goButton;
private JTextField responseField;

private JFileChooser fileChooser;

private File imagesFolder;

public TablifiForm() {
        $$$setupUI$$$();
        selectFolderButton.addActionListener(new ActionListener() {
@Override
public void actionPerformed(ActionEvent e) {
        fileChooser.showOpenDialog(mainPanel);
        imagesFolder = fileChooser.getSelectedFile();
        folderPathField.setText(imagesFolder.getAbsolutePath());
        responseField.setText("");
        }
        });
        goButton.addActionListener(new ActionListener() {
@Override
public void actionPerformed(ActionEvent e) {
        String completionState = ExtractAnnotationsHelper.extract(imagesFolder);
        responseField.setText(completionState);
        }
        });
        }

        void createUIComponents() {
        mainPanel = new JPanel();
        fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setMultiSelectionEnabled(false);

        }

/**
 * Method generated by IntelliJ IDEA GUI Designer
 * >>> IMPORTANT!! <<<
 * DO NOT edit this method OR call it in your code!
 *
 * @noinspection ALL
 */
private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel.setLayout(new GridLayoutManager(5, 4, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setEnabled(true);
        selectFolderButton = new JButton();
        selectFolderButton.setText("Select Folder...");
        mainPanel.add(selectFolderButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
final Spacer spacer1 = new Spacer();
        mainPanel.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(100, 100), new Dimension(100, 100), new Dimension(200, 200), 0, false));
final Spacer spacer2 = new Spacer();
        mainPanel.add(spacer2, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(100, 100), new Dimension(100, 100), new Dimension(200, 200), 0, false));
        goButton = new JButton();
        goButton.setText("Go");
        mainPanel.add(goButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
final Spacer spacer3 = new Spacer();
        mainPanel.add(spacer3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, new Dimension(100, 100), new Dimension(100, 100), new Dimension(200, 200), 0, false));
final Spacer spacer4 = new Spacer();
        mainPanel.add(spacer4, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, new Dimension(100, 100), new Dimension(100, 100), new Dimension(200, 200), 0, false));
        responseField = new JTextField();
        responseField.setEditable(false);
        mainPanel.add(responseField, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(300, -1), null, 0, false));
final Spacer spacer5 = new Spacer();
        mainPanel.add(spacer5, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(-1, 100), null, 0, false));
        folderPathField = new JTextField();
        folderPathField.setEditable(false);
        mainPanel.add(folderPathField, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(300, -1), null, 0, false));
        }

/**
 * @noinspection ALL
 */
public JComponent $$$getRootComponent$$$() {
        return mainPanel;
        }

}
